collections:
  games:
    output: true
    permalink: /games/:path/
  models:
    output: true
    permalink: /models/:path/
  animations:
    output: true
    permalink: /animations/:path/
baseurl: /jacobwaugh.github.io
url: "https://jacobwaugh.com/"
plugins:
  - jekyll-sitemap
