collections:
  games:
    output: true
    permalink: /games/:path/
  models:
    output: true
    permalink: /models/:path/
baseurl: /jacobwaugh.github.io
url: "https://jacob-waugh.github.io/jacobwaugh.github.io/"
plugins:
  - jekyll-sitemap
